export default function(){
    return{
        "topic1":{
            "nameClass":"FUNDAMENTACI&#211;N TE&#211;RICA",
            "classes":[
                {
                    "nameLink":"Material_teórico_El_texto_la_oración_el_párrafo_tipos_de_texto_redacción_académica",
                    "url":"https://res.cloudinary.com/doekxasxp/image/upload/v1600993597/communication/Material_te%C3%B3rico_El_texto_la_oraci%C3%B3n_el_p%C3%A1rrafo_tipos_de_texto_redacci%C3%B3n_acad%C3%A9mica-1_2_whlden.pdf"
                },
                {
                    "nameLink":"Fundamentación_Texto_Expositivo",
                    "url":"https://res.cloudinary.com/doekxasxp/image/upload/v1600993596/communication/Fundamentaci%C3%B3n_Texto_Expositivo_bfp7xx.pdf"
                },
                {
                    "nameLink":"Fundamentación_Texto_Argumentativo",
                    "url":"https://res.cloudinary.com/doekxasxp/image/upload/v1600993596/communication/Fundamentaci%C3%B3n_Texto_Argumentativo_gzytcx.pdf"
                },
                {
                    "nameLink":"Fundamentación_Derivada",
                    "url":"https://res.cloudinary.com/doekxasxp/image/upload/v1600993596/communication/FUNDAMENTACI%C3%93N_DERIVADA_morigb.pdf"
                },
                {
                    "nameLink":"Fundamentación_Extraderivada",
                    "url":"https://res.cloudinary.com/doekxasxp/image/upload/v1600993596/communication/FUNDAMENTACI%C3%93N_EXTRADERIVADA_srnzlu.pdf"
                }
            ]
        },
        "topic2":{
            "nameClass":"RECURSOS AUDIOVISUALES",
            "videos":[
                {
                    "nameLink":"Proceso de la comunicación",
                    "url":"https://www.loom.com/share/16c4f78c997649adb2a85bff762bdc97"
                },
                {
                    "nameLink":"Proceso del pensamiento",
                    "url":"https://www.loom.com/share/505e0344736d48dab486306562231096"
                },
                {
                    "nameLink":"Estructura de un Texto Expositivo",
                    "url":"https://www.loom.com/share/871d0d3085b245a29785e843ef66bb89"
                },
                {
                    "nameLink":"Estructura Precategorial de un Texto Argumentativo",
                    "url":"https://www.loom.com/share/fccfad9504df43f3b3b5314053105aa2"
                },
                {
                    "nameLink":"El Resumen y la Síntesis",
                    "url":"https://www.loom.com/share/f08b1bfe22f84845a2f431c93b8ccc87"
                }
            ]
        },
        "topic3":{
            "nameClass":"NOTAS ACADÉMICAS",
            "classes":[
                {
                    "nameLink":"Conectores_Gramaticales",
                    "url":"https://res.cloudinary.com/doekxasxp/image/upload/v1600993595/communication/AcademyNotes/Conectores_Gramaticales_j20qav.pdf"
                },
                {
                    "nameLink":"Conectores_textuales_Cassany",
                    "url":"https://res.cloudinary.com/doekxasxp/image/upload/v1600993595/communication/AcademyNotes/Conectores_textuales_Cassany-1_yyztus.pdf"
                },
            ],
            "extras":[
                {
                    "nameLink":"Cartilas_Idiomáticas.zip",
                    "url":"https://res.cloudinary.com/doekxasxp/raw/upload/v1600993591/communication/AcademyNotes/Cartillas/Cartilas_Idiom%C3%A1ticas_fbce51.zip"
                },
                {
                    "nameLink":"Nota_Académica_-_El_advervio_SOLO_y_los_pronombres_demostrativos.pptx",
                    "url":"https://res.cloudinary.com/doekxasxp/raw/upload/v1600993595/communication/AcademyNotes/Nota_Acad%C3%A9mica_-_El_advervio_SOLO_y_los_pronombres_demostrativos_1_bxvdsw.pptx"
                },
                {
                    "nameLink":"Nota_Académica_-_Investigación_de_fuentes.pptx",
                    "url":"https://res.cloudinary.com/doekxasxp/raw/upload/v1600993595/communication/AcademyNotes/Nota_Acad%C3%A9mica_-_Investigaci%C3%B3n_de_fuentes_1_oqxkgh.pptx"
                }
            ]
        },
        "topic4":{
            "nameClass":"Talleres",
            "extras":[
                {
                    "nameLink":"TALLERES.zip",
                    "url":"https://res.cloudinary.com/doekxasxp/raw/upload/v1600993598/communication/Talleres/TALLERES_zlyqty.zip"
                }
            ]
        },
        "topic5":{
            "nameClass":"Lecciones",
            "extras":[
                {
                    "nameLink":"LECCIONES.rar",
                    "url":"https://res.cloudinary.com/doekxasxp/raw/upload/v1600993597/communication/Lecciones/LECCIONES_bomexl.rar"
                },
            ]
        },
        "topic6":{
            "nameClass":"Ex&#225;menes",
            "extras":[
                {
                    "nameLink":"EXÁMENES.zip",
                    "url":"https://res.cloudinary.com/doekxasxp/raw/upload/v1600993596/communication/ExamCommunication/Examenes%20Resueltos/EX%C3%81MENES_lenskf.zip"
                },
            ]
        }
    }
}